version: '3.7'

services:
  db:
    image: postgres
    container_name: carsharing_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bruno
      - POSTGRES_PASSWORD=bruno
      - POSTGRES_DB=carsharingdb
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: carsharing
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379   

volumes:
  pgdata:
    driver: local
